### ISSUE TITLE
No image preview while sharing blog posts to social sites (Shows blank)

### ISSUE THREAD

**Issue by mbaljeetsingh** [netlify-templates/victor-hugo#100]
I think it is related to meta og:image tag (not sure). If it is the case, how can I update it.

**- *bug*

**- No image preview while sharing**

**- If it try to share this link (https://www.baljeetsingh.in/blog/adding-seo-support-to-angular-6-application/)  on any social site, Image preview not showing**

**- It should show the image preview**

**- Site is live on Netlify**

**Comment by jhabdas** [comment]
Check if Hugo's Open Graph template is included in the theme. https://github.com/spf13/hugo/blob/142558719324aa1628541d556ef1fa2d123f1e68/tpl/tplimpl/template_embedded.go#L159-L201

**Comment by erquhart** [comment]
I'm seeing it working, meta tags are in place. You can test here:
https://cards-dev.twitter.com/validator
