### ISSUE TITLE
Submenu problem

### ISSUE THREAD

**Issue by fgallaire** [netlify-templates/victor-hugo#126]
https://github.com/LordMathis/hugo-theme-nix/issues/47

https://f.gallai.re the Layouts submenu doesn't work, as the problem seems not to be in the Nix theme, maybe it's in Victor Hugo ?

```
  [[menu.header]]
    identifier = "layout"
    name = "Layouts"
    weight = 1
    url = "/layouts"
  [[menu.header]]
    parent = "layout"
    name = "Viet US"
    url = "/viet-us"
  [[menu.header]]
    parent = "layout"
    name = "QĐERTY"
    url = "/qderty"
```

**Comment by erquhart** [comment]
Really seems like an implementation thing, not certain where this boilerplate would be hurting your use case, but I'll leave this open in case someone wants to dig in.

**Comment by fgallaire** [comment]
Hello @erquhart, maybe update Hugo will fix the problem.

What is the right way to do it when using victor-hugo ?

**Comment by erquhart** [comment]
That'd be awesome, but note that Hugo is not 1.0 yet, so there will be breaking changes to check for in Hugo's release notes. This project uses `hugo-bin` as an npm dependency: https://github.com/fenneclab/hugo-bin
