### ISSUE TITLE
Build error in docker container

### ISSUE THREAD

**Issue by b1551** [netlify-templates/victor-hugo#139]
Hi, I'm trying to build (gulp build) the project within docker container and I'm getting the following error:

[11:28:00] Starting 'build'...
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 1: /usr/src/app/node_modules/hugo-bin/vendor/hugo: ����: not found
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 1: /usr/src/app/node_modules/hugo-bin/vendor/hugo: ?: not found
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 1: /usr/src/app/node_modules/hugo-bin/vendor/hugo: ?�R: not found
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 1: /usr/src/app/node_modules/hugo-bin/vendor/hugo: ?: not found
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 2: /usr/src/app/node_modules/hugo-bin/vendor/hugo: hH__PAGEZEROx__TEXT?__text__TEXT��__rodata__TEXT���N��__symbol_stub1__TEXT�7���7�__typelink__TEXT�8��g�8�__itablink__TEXTH��xH��__gosymtab__TEXT������__gopclntab__TEXT����[����__DATA?��__nl_symbol_ptr__DATA?#__noptrdata__DATA: File name too long
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 3: /usr/src/app/node_modules/hugo-bin/vendor/hugo: : not found
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 4: /usr/src/app/node_modules/hugo-bin/vendor/hugo: �: not found
/usr/src/app/node_modules/hugo-bin/vendor/hugo: 5: /usr/src/app/node_modules/hugo-bin/vendor/hugo: Syntax error: end of file unexpected (expecting ")")
[11:28:00] 'build' errored after 22 ms

My dockerfile looks like this:
FROM node:8.12.0 as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
COPY . /usr/src/app
RUN npm run build

It's working fine outside docker.  I would appreciate any help you could provide. Thanks

**Comment by shauntarves** [comment]
I'm actually having the same issue. Anyone have a clue what the hell is going on here?

```
> cross-env NODE_ENV=production webpack --config webpack.prod.js --hot --inline

Hash: 43b71641785fea73c4e6
Version: webpack 4.29.0
Time: 2129ms
Built at: 01/30/2019 9:36:31 PM
         Asset       Size  Chunks             Chunk Names
   fonts/.keep    0 bytes          [emitted]  
main.43b71.css  505 bytes       0  [emitted]  main
 main.43b71.js   13.1 KiB       0  [emitted]  main
Entrypoint main = main.43b71.css main.43b71.js
[0] ./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js!./src/css/main.css 39 bytes {0} [built]
[1] ./src/index.js 120 bytes {0} [built]
[2] ./src/css/main.css 1.5 KiB {0} [built]
    + 3 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js!node_modules/sass-loader/lib/loader.js!src/css/main.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js!./src/css/main.css 980 bytes {0} [built]
        + 1 hidden module

> temp@0.0.1 build:hugo /app
> hugo -d ../dist -s site -v

/app/node_modules/hugo-bin/vendor/hugo: 1: /app/node_modules/hugo-bin/vendor/hugo: ����: not found
/app/node_modules/hugo-bin/vendor/hugo: 2: /app/node_modules/hugo-bin/vendor/hugo: Syntax error: "(" unexpected
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! temp@0.0.1 build:hugo: `hugo -d ../dist -s site -v`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the temp@0.0.1 build:hugo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T21_36_31_808Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! temp@0.0.1 build: `npm run build:webpack && npm run build:hugo`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the temp@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T21_36_31_824Z-debug.log
```

**Comment by jasonatrtr** [comment]
Your Hugo config has an error in it.

**Comment by shauntarves** [comment]
Definitely not...hugo runs perfectly fine outside of docker

**Comment by shauntarves** [comment]
Solved. This error is caused by the copying of `.` into the Docker container. This *also* copies the local `node_modules` folder, which has the host OS's hugo executable file. In my case, running on a Mac, the filetype was a Mach O executable, not an LSB executable.
