### ISSUE TITLE
Google says sitemap is invalid

### ISSUE THREAD

**Issue by andrewlynch** [netlify-templates/victor-hugo#142]
Google Search Console says that sitemap is invalid because it contains a relative URL without the domain. 

My baseURL is set to "/" and this causes issues in development if this is set to a fixed url.

The problem has been [solved by other Hugo boilerplates](https://github.com/indigotree/atlas/issues/38) by telling Netlify to inject the correct `baseURL` on build. Has anyone managed to do this successfully?

**Comment by erquhart** [comment]
The fix looks [simple enough](https://github.com/indigotree/atlas/pull/39/files), would definitely take a PR for it if someone can implement and test.

**Comment by jSwtch** [comment]
Anyone else having the same issue - I just created a sitemap.xml in the layouts folder, it wil overide the default hugo. Important line is adding your url to the <loc>

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  {{ range .Data.Pages }}
  <url>
    <loc>**https://my-url/com**{{ .Permalink }}</loc>{{ if not .Lastmod.IsZero }}
    <lastmod>{{ safeHTML ( .Lastmod.Format "2006-01-02T15:04:05-07:00" ) }}</lastmod>{{ end }}{{ with .Sitemap.ChangeFreq }}
    <changefreq>{{ . }}</changefreq>{{ end }}{{ if ge .Sitemap.Priority 0.0 }}
     <priority>{{ .Sitemap.Priority }}</priority>{{ end }}{{ if .IsTranslated }}{{ range .Translations }}
    <xhtml:link
                rel="alternate"
                hreflang="{{ .Lang }}"
                href="{{ .Permalink }}"
                />{{ end }}
    <xhtml:link
                rel="alternate"
                hreflang="{{ .Lang }}"
                href="{{ .Permalink }}"
                />{{ end }}
  </url>
  {{ end }}
</urlset>
```

**Comment by erquhart** [comment]
@andrewlynch is this a viable solution for you?
