### ISSUE TITLE
EventStream / flatmap-stream Dependency Issues

### ISSUE THREAD

**Issue by jdsimcoe** [netlify-templates/victor-hugo#143]
I ran `npm ls event-stream flatmap-stream` in my clone of this repo per https://github.com/dominictarr/event-stream/issues/116 and `victor-hugo` shows a dependency of `event-stream` and `flatmap-stream`:

```sh
victor-hugo@1.0.0
└─┬ gulp-inject@4.3.2
  └─┬ event-stream@3.3.6
    └── flatmap-stream@0.1.0
```

I'm not sure if the `0.1.0` version is concerning since it looks like the rogue injection happened post `0.1.1` but I at least wanted to post this here to get some extra eyes on it.

**Comment by erquhart** [comment]
Would be resolved by #138 once merged.
