### ISSUE TITLE
Invalid Host/Origin header

### ISSUE THREAD

**Issue by InsOpDe** [netlify-templates/victor-hugo#155]
# Bug-report
I believe that there is something broken with the current behaviour of the filewatcher/websocket.
If I make changes on the watched files, they won't get reflected on localhost:3000.
When opening the console every second I get following error messages:

> Invalid Host/Origin header
> [WDS] Disconnected!

## How to reproduce
Clone the project, install it with npm then run it with `npm start`. Your browser opens `localhost:3000` And first, the styles arent applied and no error message. However, upon reloading the error I described above occurs. I.e. no more auto-reloading upon file-changes and the console is full of errors.
Tried it with Chromium 71.0.3578.80 and Firefox 64.0

## Expected Behaviour
Shouldn't throw errors in console, page should reload properly on filechanges (to be clear, the hugo-cli detects file changes, but the browser wont reload)

Nodeversion: 9.11.2
npm: 5.6.0
OS: Ubuntu 18.04.1

Thanks in Advance

**Comment by eliwilliamson** [comment]
@InsOpDe see [here](https://github.com/webpack/webpack-dev-server/issues/1604) for solution

**Comment by InsOpDe** [comment]
Thanks - Im closing it now as it is not related to this repository
