### ISSUE TITLE
No error details on SASS compilation error

### ISSUE THREAD

**Issue by SilencerWeb** [netlify-templates/victor-hugo#174]
**- Do you want to request a *feature* or report a *bug*?**
feature

Please, add error details on SASS compilation error. Right now I get an error "Failed to compile." but lol, wtf is it? How to find out what's wrong?

![image](https://user-images.githubusercontent.com/20713191/56724716-fa957480-6764-11e9-84bf-fab52ae56017.png)

**Comment by tomanistor** [comment]
@SilencerWeb, in `webpack.dev.js`, find the `devServer` object and either completely remove `stats: 'none'` or change its value to something else like `errors-only`, `minimal`, `normal`, 
 or `verbose`.

This is a Webpack Dev Server setting that for some reason is turned off by default. 
https://webpack.js.org/configuration/dev-server/#devserverstats-

**Comment by erquhart** [comment]
A PR for better error messaging would be welcome if anyone is up for it 👍

**Comment by tomanistor** [comment]
Would be happy to!
