### ISSUE TITLE
How to use yarn start to listen on 0.0.0.0 address ?

### ISSUE THREAD

**Issue by joao-parana** [netlify-templates/victor-hugo#233]
**- Do you want to request a *feature* or report a *bug*?**

Only a request to provide a information on README

**- What is the current behavior?**

`yarn start` listen only on localhost

**- What is the expected behavior?**

I need to test the site using it from another host.

**- Please mention your node.js, NPM, Hugo and operating system version.**

N/A

**Comment by abyss** [comment]
If you want to do this, you can modify the `start:webpack` script in package.json to have ` --host 0.0.0.0` after the `--hot`.

The automatic opening of your browser seems to break (it tries to open the 0.0.0.0 address), but you can open the site manually (via localhost or your ip address) and others can access it remotely (provided firewalls are all proper).
