### ISSUE TITLE
Add method for managing separate webpack configs for production/development

### ISSUE THREAD

**Issue by 01ivr3** [netlify-templates/victor-hugo#69]
For example:

https://webpack.js.org/guides/production/

or [One webpack config to rule them all — environments that is](https://medium.com/@ryandrewjohnson/one-webpack-config-to-rule-them-all-environments-that-is-277457769779)

**Comment by erquhart** [comment]
Agreed, a PR for this would be great.

**Comment by 01ivr3** [comment]
@erquhart apologies, I'm not too familiar with what the best way to implement conditional webpack configs for victor-hugo. I resorted to a hacky method of simply duplicating and renaming some of the gulp tasks to have separate ones for both production and development. Not idea, but worked for the project I was working on.

**Comment by erquhart** [comment]
No problem, thanks for opening the issue! We'll keep it around and see who wants to take a stab.

**Comment by andrewgleave** [comment]
I hacked together a 5 min solution to this here:

https://github.com/andrewgleave/victor-hugo/commit/0ce597965dc48035e687432c9c78c0f9d84ab204

If there's interest, I'll tidy it up and send a PR.

**Comment by inian** [comment]
This should be fixed with https://github.com/netlify-templates/victor-hugo/commit/c2e09f4e49e995c6a3e5dec95611cf1d51308962

**Comment by erquhart** [comment]
Ah, agreed.
