### ISSUE TITLE
How can i use victor-hugo with hugo multilingual

### ISSUE THREAD

**Issue by erolabzait** [netlify-templates/victor-hugo#71]
Hello,

Thank you for this great repo. 
When i use it with hugo multilangual in the dist folder i have css, en, de, es and in netlify i created a domain for each language folder. Is there a way to use the css, js, images folders without a symlink/copy in each language folder?

A solution will be to copy the css folder in the site/static/ and let hugo handle the duplication for each lang, but it doesn't feel right.

All the best,
Erol

**Comment by erquhart** [comment]
If they're separate domains, just copy the files during the build, that's the standard approach.

**Comment by jhabdas** [comment]
@erolabzait yarn uses [CrowdIn](https://crowdin.com/) for i18n on [their Jekyll site](https://github.com/yarnpkg/website). there are some js modules which assist in reverse-ip geolocation you could use alongside crowdin to suggest languages depending on your implementation and layout

**Comment by erolabzait** [comment]
When i use the default victor-hugo with hugo v0.37 i get this warnings

```
WARN 2018/03/03 15:54:22 No translation bundle found for default language "en"
WARN 2018/03/03 15:54:22 Translation func for language en not found, use default.
WARN 2018/03/03 15:54:22 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
WARN 2018/03/03 15:54:22 [en] Unable to locate layout for "404": [404.html]
```
