### ISSUE TITLE
How to add hash to static assets?

### ISSUE THREAD

**Issue by shuaibird** [netlify-templates/victor-hugo#79]
It seems currently this template doesn't add a hash to static assets automatically. Not sure whether this feature has been shipped already.

**Comment by erquhart** [comment]
Victor Hugo currently uses Gulp for copying assets, but still using Webpack for other things. I'd like to see use Webpack for everything, with the [copy plugin](https://github.com/webpack-contrib/copy-webpack-plugin) for moving static assets, and a hash can be added in the copy plugin config. For example:

```js
[
  new CopyWebpackPlugin([
    {
      from: 'src/',
      to: 'dest/[name]-[hash].[ext]',
    }
  ])
]
```

**Comment by shuaibird** [comment]
make sense. It would be much clearer to use webpack solely.

**Comment by jhabdas** [comment]
> It seems currently this template doesn't add a hash to static assets automatically.

Cache strategies vary wildly based on how a site is hosted. For example, if you're using CloudFront as a CDN and deploying with something like the very excellent [`s3_website`](https://github.com/laurilehmijoki/s3_website) you don't even need to think about caching beyond some simple YAML config. I'm not sure how Netlify handles cache invalidation but I'd imagine `victor-hugo` should probably remain highly optimized to fit their environment.

**Comment by jhabdas** [comment]
Hugo `0.43` [introduces](https://gohugo.io/news/0.43-relnotes/) the ability to fingerprint assets, concatenate and minify files and will personally deliver a pony to your doorstep if you ask it to.

**Comment by jhabdas** [comment]
Hugo 0.43 introduces the ability to fingerprint assets, concatenate and minify files and will personally deliver a pony to your doorstep if you ask it to. `hugo deliver --ponyToDoorstep`

**Comment by jhabdas** [comment]
Hugo 0.43 [introduces](https://gohugo.io/news/0.43-relnotes/) the ability to fingerprint assets, concatenate and minify files, do stuff with sass and postcss and (I heard) will personally deliver a pony to your doorstep if you ask it nicely.

**Comment by jhabdas** [comment]
Hugo 0.43 and above now supports fingerprinting naively, Webpak not necessary

**Comment by erquhart** [comment]
Latest hugo-bin is 0.42, we'll get 0.43 when available.

@shuaibird agreed, we should drop gulp.

**Comment by tisba** [comment]
hugo is now at 0.50. Is @erquhart's usage of the copy plugin still the way to go to get fingerprinted assets?

**Comment by erquhart** [comment]
Hmm just noticed a [recent PR](https://github.com/netlify-templates/victor-hugo/pull/128) updated Hugo. Assuming that didn't break anything, Hugo's native fingerprinting is now available in this starter. [Docs here](https://gohugo.io/hugo-pipes/fingerprint/).
