### ISSUE TITLE
PostCSS errors stops Gulp watch

### ISSUE THREAD

**Issue by Handja** [netlify-templates/victor-hugo#86]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When post-css detects errors on css file, gulp watch stops working.

**- What is the expected behavior?**
Just display the error on console without stoping gulp watch.

**- Please mention your node.js, NPM, Hugo and operating system version.**
node 6.10.0
npm 6.0.0
hugo 0.37

**Comment by Juhannuspukki** [comment]
This is very annoying, especially when trying to compile bootstrap from source. I forked this and replaced postCSS with gulp-sass.

**Comment by erquhart** [comment]
Like other issues, this would be resolved by just using Webpack. Not the only way to fix obviously, but it's the fix that's most likely to happen.

**Comment by jSwtch** [comment]
Just curious how does the hugo-bin relate to the official releases? 
npm hugo-bin 0.39.0 (latest)
official hugo v0.51 (latest)

**Comment by DirtyF** [comment]
@erquhart this one can be closed too I guess 😄
