### ISSUE TITLE
How to change post permalink

### ISSUE THREAD

**Issue by sajaldotco** [netlify-templates/victor-hugo#98]
How to change post permalink "example.com/post/new-post.html" to "example.com/new-post.html"

**Comment by crgeary** [comment]
I'm assuming your example should read: `/post/new-post/` to `/post/new-post/` as I don't believe Hugo supports `.html` extensions on single pages (it's certainly not default functionality).

To change permalinks in Hugo, see: https://gohugo.io/content-management/urls/#permalinks

```
[permalinks]
  post = "/:title"
```

Here is some reasoning for why Hugo doesn't have support for `new-post.html` - https://discourse.gohugo.io/t/links-without-a-trailing-slash/831/16

**Comment by jhabdas** [comment]
He's looking to do some SEO magic to shorten the link. Does Netlify support redirects?
