### ISSUE TITLE
How to utilize hugo's new image processing

### ISSUE THREAD

**Issue by eliwilliamson** [netlify-templates/victor-hugo#99]
Given the separated file structure, the images are not located in the hugo build scope so you can't utilize the "resources" functionality for image processing w/ hugo. Am i missing something? How can i utilize this image processing feature? can it be done without reorganizing the file strucuture?

Here is more info on hugo's image processing functionality:
https://gohugo.io/content-management/image-processing/

**Comment by jhabdas** [comment]
Here's a reference implementation in case you're looking to fork https://git.habd.as/comfusion/after-dark#post-images

**Comment by jSwtch** [comment]
I solved this issue here: https://discourse.gohugo.io/t/page-bundle-question-content-structure-for-image-processing-solved/14860/4

**Comment by erquhart** [comment]
Awesome, thanks @jSwtch 👍
